version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - '27017:27017'
    volumes:
      - ~/Library/CloudStorage/OneDrive-Accenture/Projetos/Personal/Bayer/mongodb:/data/db:z

volumes:
  mongo-data:
