version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo_container
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
