name: frontend

services:
  app:
    container_name: app
    image: frontend-app
    build:
      context: ../
      dockerfile: ./infra/app/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ../:/app
      - /app/node_modules
    command: pnpm dev
