version: '3.8'

name: next-product-site-db

services:
  mongodb:
    container_name: next-product-site-db
    image: bitnami/mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_ADVERTISED_HOSTNAME: '127.0.0.1'
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: root
    volumes:
      - mongodb-data:/bitnami/mongodb

volumes:
  mongodb-data:
